#!/usr/bin/env sh

# Wrapper around mf2vcf.py: convert an .MF.predictions file to .vcf.gz
usage="usage: $0 some.MF.predictions refseq.fa [some.vcf.gz]"
if test $# -lt 2; then
    echo $usage; exit 1
fi

MFdir=`dirname $0`
mf2vcfpy=$MFdir/mf2vcf.py
MFpred=$1
refseq=$2
bn=`basename $MFpred .MF.predictions`
vcfgz=${3:-$bn.vcf.gz}

$mf2vcfpy $refseq < $MFpred |
    bcftools sort -Oz -o $vcfgz
bcftools index --tbi $vcfgz
